# Identificadores del proyecto
sonar.projectKey=hospital_api
sonar.projectName=Hospital API - Proyecto P1
sonar.projectVersion=1.0.0

# Directorio base para el análisis (la raíz del proyecto)
sonar.sources=.

# 🚨 EL FILTRO CRÍTICO: Exclusiones estrictas
sonar.exclusions=node_modules/**, public/**, **/*.test.js, coverage/**, src/testRunner.js

# (Opcional) Vincular el reporte de cobertura de Jest si lo necesitas
sonar.javascript.lcov.reportPaths=coverage/lcov.info